/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#EC4899",
          "primary-content": "#000000",
          secondary: "#F4A6C0",
          "secondary-content": "#1A1A1A",
          accent: "#FFC2D1",
          "accent-content": "#000000",
          neutral: "#FFFFFF",
          "neutral-content": "#000000",
          "base-100": "#FFFFFF",
          "base-200": "#F8F8F8",
          "base-300": "#EDEDED",
          "base-content": "#1A1A1A",
          info: "#EC4899",
          success: "#F78CA0",
          warning: "#FFC75F",
          error: "#FF4D4D",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#EC4899",
          "primary-content": "#000000",
          secondary: "#D93680",
          "secondary-content": "#FFFFFF",
          accent: "#FF85B3",
          "accent-content": "#000000",
          neutral: "#FFFFFF",
          "neutral-content": "#000000",
          "base-100": "#1C1C1C",
          "base-200": "#121312",
          "base-300": "#000000",
          "base-content": "#FFFFFF",
          info: "#FF85B3",
          success: "#F78CA0",
          warning: "#FFC75F",
          error: "#FF4D4D",
          "--rounded-btn": "9999rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      fontFamily: { "space-grotesk": ["Space Grotesk", "sans-serif"] },
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
      colors: {
        gray: "#303033",
      },
    },
  },
};
